---
# handlers file for falcon_install
  - name: CrowdStrike Falcon | Restart Falcon Sensor
    ansible.builtin.service:
      name: falcon-sensor
      state: "{{ falcon_service_state | default('restarted') }}"
