---
- name: CrowdStrike Falcon | Authenticate to CrowdStrike API
  ansible.windows.win_uri:
    url: "https://{{ falcon_cloud }}/oauth2/token"
    method: POST
    body: "client_id={{ falcon_client_id }}&client_secret={{ falcon_client_secret }}"
    return_content: true
    status_code: 201
    headers:
      content-type: application/x-www-form-urlencoded
  register: falcon_api_oauth2_token

- name: CrowdStrike Falcon | Detect Target CID Based on Credentials
  ansible.windows.win_uri:
    url: https://{{ falcon_cloud }}/sensors/queries/installers/ccid/v1
    method: GET
    return_content: true
    headers:
      authorization: "Bearer {{ falcon_api_oauth2_token.json.access_token }}"
      Content-Type: application/json
  register: falcon_api_target_cid

- name: "CrowdStrike Falcon | Build API Query"
  ansible.builtin.set_fact:
    falcon_os_query: "{{ 'os:\"' + falcon_target_os + '\"+os_version:\"' + falcon_os_version + '\"' }}"

- name: CrowdStrike Falcon | Get list of filtered Falcon sensors
  ansible.windows.win_uri:
    url: "https://{{ falcon_cloud }}/sensors/combined/installers/v1?filter={{ falcon_os_query | urlencode }}"
    method: GET
    return_content: true
    headers:
      authorization: "Bearer {{ falcon_api_oauth2_token.json.access_token }}"
      Content-Type: application/json
  register: falcon_api_installer_list

- name: CrowdStrike Falcon | Download Falcon Sensor Installation Package
  ansible.windows.win_get_url:
    url: "https://{{ falcon_cloud }}/sensors/entities/download-installer/v1?id={{ falcon_api_installer_list.json.resources[falcon_sensor_version | int].sha256 }}"
    dest: "{{ falcon_windows_tmp_dir }}\\{{ falcon_api_installer_list.json.resources[falcon_sensor_version | int].name }}"
    checksum: "{{ falcon_api_installer_list.json.resources[0].sha256 }}"
    checksum_algorithm: sha256
    headers:
      authorization: "Bearer {{ falcon_api_oauth2_token.json.access_token }}"
  register: falcon_sensor_download

- name: CrowdStrike Falcon | Set CID received from API
  ansible.builtin.set_fact:
    falcon_cid: "{{ falcon_api_target_cid.json.resources[0] }}"
  when: not falcon_cid

- name: CrowdStrike Falcon | Set full file download path
  ansible.builtin.set_fact:
    falcon_sensor_pkg: "{{ falcon_sensor_download.dest }}"
