---
# tasks file for falcon_uninstall
- name: Linux Block
  block:
    - include_tasks: uninstall.yml
  when:
    - ansible_os_family != "Windows"
  become: true
  become_user: root

- name: Windows Block
  block:
    - include_tasks: win_uninstall.yml
  when:
    - ansible_os_family == "Windows"
  become: true
  become_method: "{{ falcon_windows_become_method }}"
  become_user: "{{ falcon_windows_become_user }}"
