---
- name: CrowdStrike Falcon | Find Windows installer in Package Cache
  ansible.windows.win_find:
    paths: C:\ProgramData\Package Cache
    patterns: ^(WindowsSensor.*\.)(exe)$
    recurse: yes
    use_regex: yes
  register: falcon_win_sensor_cache

- name: CrowdStrike Falcon | Remove Falcon Sensor (Windows)
  ansible.windows.win_package:
    path: "{{ falcon_win_sensor_cache.files[0].path }}"
    state: absent
    creates_service: csfalconservice
    arguments: '/uninstall /quiet {{ falcon_windows_uninstall_args }}'
  when:
    - falcon_win_sensor_cache.files | length > 0
    - ansible_facts['os_family'] == "Windows"

# The directory C:\Windows\System32\drivers\CrowdStrike is not present
- name: CrowdStrike Falcon | Check for Windows Sensor directory (Windows)
  ansible.windows.win_stat:
    path: C:\Windows\System32\drivers\CrowdStrike
  register: falcon_win_sensor_dir

- name: CrowdStrike Falcon | Assert Windows Sensor directory is absent (Windows)
  ansible.builtin.assert:
    that:
      - not falcon_win_sensor_dir.stat.exists

# The registry key HKLM\System\Crowdstrike does not appear in the registry
- name: CrowdStrike Falcon | Check for Windows Sensor registry key (Windows)
  ansible.windows.win_reg_stat:
    path: HKLM:\System\Crowdstrike
  register: falcon_win_sensor_reg

- name: CrowdStrike Falcon | Assert Windows Sensor registry key is absent (Windows)
  ansible.builtin.assert:
    that:
      - not falcon_win_sensor_reg.exists
