---
# tasks file for falcon_install
- block:
    - ansible.builtin.include_tasks: preinstall.yml
      # noqa unnamed-task 502

- block:
    - ansible.builtin.include_tasks: url.yml
      # noqa unnamed-task 502
  when:
    - falcon_install_method == "url"
    - ansible_os_family != "Windows"

- block:
    - ansible.builtin.include_tasks: api.yml
      # noqa unnamed-task 502
  when:
    - falcon_install_method == "api"
    - ansible_os_family != "Windows"

- block:
    - ansible.builtin.include_tasks: file.yml
      # noqa unnamed-task 502
  when:
    - falcon_install_method == "file"

- block:
    - ansible.builtin.include_tasks: win_api.yml
      # noqa unnamed-task 502
  when:
    - falcon_install_method == "api"
    - ansible_os_family == "Windows"

- block:
    - ansible.builtin.include_tasks: install.yml
      # noqa unnamed-task 502
  when:
    - ansible_os_family != "Windows"
  become: true
  become_user: root

- block:
    - ansible.builtin.include_tasks: win_install.yml
      # noqa unnamed-task 502
  when:
    - ansible_os_family == "Windows"
  become: true
  become_method: "{{ falcon_windows_become_method }}"
  become_user: "{{ falcon_windows_become_user }}"
