---
# vars file for falcon_installation
linux_packagers: "{{ rpm_packagers + dpkg_packagers }}"

rpm_packagers:
  - yum
  - rpm
  - dnf
  - zypper

dpkg_packagers:
  - apt

falcon_gpg_key: falcon-sensor.gpg
falcon_gpg_key_dest: /tmp/falcon-sensor.gpg
