---
# handlers file for falcon_configure
  - name: CrowdStrike Falcon | Restart Falcon Sensor
    ansible.builtin.service:
      name: falcon-sensor
      state: "{{ falcon_service_state | default('restarted') }}"
      enabled: yes
    when: info.falconctl_info.cid
    become: yes
