name: Python Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pylint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pylint bandit
    - name: Lint with flake8
      run:
        flake8 ./plugins/
    - name: Lint with pylint
      run: |
        pylint ./plugins/
    - name: Lint with bandit
      run: |
        bandit  -l -i -r ./plugins/
