name: Release

on:
  release:
    types:
      - created

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install pip
        run: |
          python -m pip install --upgrade pip
          pip install ansible
      - name: Create release artifacts
        run: |
          ansible-galaxy collection build
      - name: Release artifacts to GitHub
        run: |
          gh release upload $TAG ./crowdstrike-falcon*.tar.gz
        env:
          TAG: ${{ github.event.release.tag_name }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
